
package com.alexanderwjz.servicepushAsAlias;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JpushAsAliasImplService", targetNamespace = "http://serviceImpl.alexanderwjz.com/", wsdlLocation = "http://localhost:8080/JpushService/service/jpushServicePushAsAlias?wsdl")
public class JpushAsAliasImplService
    extends Service
{

    private final static URL JPUSHASALIASIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JPUSHASALIASIMPLSERVICE_EXCEPTION;
    private final static QName JPUSHASALIASIMPLSERVICE_QNAME = new QName("http://serviceImpl.alexanderwjz.com/", "JpushAsAliasImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JpushService/service/jpushServicePushAsAlias?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JPUSHASALIASIMPLSERVICE_WSDL_LOCATION = url;
        JPUSHASALIASIMPLSERVICE_EXCEPTION = e;
    }

    public JpushAsAliasImplService() {
        super(__getWsdlLocation(), JPUSHASALIASIMPLSERVICE_QNAME);
    }

    public JpushAsAliasImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JPUSHASALIASIMPLSERVICE_QNAME, features);
    }

    public JpushAsAliasImplService(URL wsdlLocation) {
        super(wsdlLocation, JPUSHASALIASIMPLSERVICE_QNAME);
    }

    public JpushAsAliasImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JPUSHASALIASIMPLSERVICE_QNAME, features);
    }

    public JpushAsAliasImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JpushAsAliasImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JpushAsAlias
     */
    @WebEndpoint(name = "JpushAsAliasImplPort")
    public JpushAsAlias getJpushAsAliasImplPort() {
        return super.getPort(new QName("http://serviceImpl.alexanderwjz.com/", "JpushAsAliasImplPort"), JpushAsAlias.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JpushAsAlias
     */
    @WebEndpoint(name = "JpushAsAliasImplPort")
    public JpushAsAlias getJpushAsAliasImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceImpl.alexanderwjz.com/", "JpushAsAliasImplPort"), JpushAsAlias.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JPUSHASALIASIMPLSERVICE_EXCEPTION!= null) {
            throw JPUSHASALIASIMPLSERVICE_EXCEPTION;
        }
        return JPUSHASALIASIMPLSERVICE_WSDL_LOCATION;
    }

}
