
package com.alexanderwjz.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JpushAllImplService", targetNamespace = "http://serviceImpl.alexanderwjz.com/", wsdlLocation = "http://localhost:8080/JpushService/service/jpushServicePushAll?wsdl")
public class JpushAllImplService
    extends Service
{

    private final static URL JPUSHALLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JPUSHALLIMPLSERVICE_EXCEPTION;
    private final static QName JPUSHALLIMPLSERVICE_QNAME = new QName("http://serviceImpl.alexanderwjz.com/", "JpushAllImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JpushService/service/jpushServicePushAll?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JPUSHALLIMPLSERVICE_WSDL_LOCATION = url;
        JPUSHALLIMPLSERVICE_EXCEPTION = e;
    }

    public JpushAllImplService() {
        super(__getWsdlLocation(), JPUSHALLIMPLSERVICE_QNAME);
    }

    public JpushAllImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JPUSHALLIMPLSERVICE_QNAME, features);
    }

    public JpushAllImplService(URL wsdlLocation) {
        super(wsdlLocation, JPUSHALLIMPLSERVICE_QNAME);
    }

    public JpushAllImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JPUSHALLIMPLSERVICE_QNAME, features);
    }

    public JpushAllImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JpushAllImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JpushAll
     */
    @WebEndpoint(name = "JpushAllImplPort")
    public JpushAll getJpushAllImplPort() {
        return super.getPort(new QName("http://serviceImpl.alexanderwjz.com/", "JpushAllImplPort"), JpushAll.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JpushAll
     */
    @WebEndpoint(name = "JpushAllImplPort")
    public JpushAll getJpushAllImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceImpl.alexanderwjz.com/", "JpushAllImplPort"), JpushAll.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JPUSHALLIMPLSERVICE_EXCEPTION!= null) {
            throw JPUSHALLIMPLSERVICE_EXCEPTION;
        }
        return JPUSHALLIMPLSERVICE_WSDL_LOCATION;
    }

}
