
package com.alexanderwjz.serviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.alexanderwjz.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Jpush", targetNamespace = "http://service.alexanderwjz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Jpush {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "pushAllNotice", targetNamespace = "http://service.alexanderwjz.com/", className = "com.alexanderwjz.service.PushAllNotice")
    @ResponseWrapper(localName = "pushAllNoticeResponse", targetNamespace = "http://service.alexanderwjz.com/", className = "com.alexanderwjz.service.PushAllNoticeResponse")
    public void pushAllNotice(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "pushAsAliasUdM", targetNamespace = "http://service.alexanderwjz.com/", className = "com.alexanderwjz.service.PushAsAliasUdM")
    @ResponseWrapper(localName = "pushAsAliasUdMResponse", targetNamespace = "http://service.alexanderwjz.com/", className = "com.alexanderwjz.service.PushAsAliasUdMResponse")
    public void pushAsAliasUdM(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
